# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:/Users/Joel/Documents/Sparkle-Neuroscience-Converter/main.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setEnabled(True)
        MainWindow.resize(431, 510)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("horsey4.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButton_start = QtGui.QPushButton(self.centralwidget)
        self.pushButton_start.setObjectName(_fromUtf8("pushButton_start"))
        self.horizontalLayout_2.addWidget(self.pushButton_start)
        self.gridLayout.addLayout(self.horizontalLayout_2, 5, 0, 1, 1)
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.lineEdit_file_name = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_file_name.setObjectName(_fromUtf8("lineEdit_file_name"))
        self.gridLayout_8.addWidget(self.lineEdit_file_name, 2, 0, 1, 2)
        self.textEdit = QtGui.QTextEdit(self.centralwidget)
        self.textEdit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.textEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.gridLayout_8.addWidget(self.textEdit, 13, 0, 1, 3)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_8.addWidget(self.label_3, 14, 0, 1, 1)
        self.progressBar_data = QtGui.QProgressBar(self.centralwidget)
        self.progressBar_data.setProperty("value", 0)
        self.progressBar_data.setObjectName(_fromUtf8("progressBar_data"))
        self.gridLayout_8.addWidget(self.progressBar_data, 18, 0, 1, 3)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_8.addWidget(self.label_2, 3, 0, 1, 1)
        self.pushButton_browse_open = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_browse_open.sizePolicy().hasHeightForWidth())
        self.pushButton_browse_open.setSizePolicy(sizePolicy)
        self.pushButton_browse_open.setObjectName(_fromUtf8("pushButton_browse_open"))
        self.gridLayout_8.addWidget(self.pushButton_browse_open, 2, 2, 1, 1)
        self.lineEdit_output_directory = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_output_directory.setObjectName(_fromUtf8("lineEdit_output_directory"))
        self.gridLayout_8.addWidget(self.lineEdit_output_directory, 6, 0, 1, 2)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_8.addWidget(self.label_4, 16, 0, 1, 1)
        self.progressBar_meta = QtGui.QProgressBar(self.centralwidget)
        self.progressBar_meta.setProperty("value", 0)
        self.progressBar_meta.setObjectName(_fromUtf8("progressBar_meta"))
        self.gridLayout_8.addWidget(self.progressBar_meta, 15, 0, 1, 3)
        self.comboBox_threshold = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_threshold.sizePolicy().hasHeightForWidth())
        self.comboBox_threshold.setSizePolicy(sizePolicy)
        self.comboBox_threshold.setMinimumSize(QtCore.QSize(110, 0))
        self.comboBox_threshold.setObjectName(_fromUtf8("comboBox_threshold"))
        self.gridLayout_8.addWidget(self.comboBox_threshold, 10, 0, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout_comments = QtGui.QVBoxLayout()
        self.verticalLayout_comments.setObjectName(_fromUtf8("verticalLayout_comments"))
        self.label_comments = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_comments.setFont(font)
        self.label_comments.setObjectName(_fromUtf8("label_comments"))
        self.verticalLayout_comments.addWidget(self.label_comments)
        self.lineEdit_comments = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_comments.setObjectName(_fromUtf8("lineEdit_comments"))
        self.verticalLayout_comments.addWidget(self.lineEdit_comments)
        self.gridLayout_2.addLayout(self.verticalLayout_comments, 1, 1, 1, 1)
        self.verticalLayout_test = QtGui.QVBoxLayout()
        self.verticalLayout_test.setObjectName(_fromUtf8("verticalLayout_test"))
        self.label_test = QtGui.QLabel(self.centralwidget)
        self.label_test.setMinimumSize(QtCore.QSize(110, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_test.setFont(font)
        self.label_test.setObjectName(_fromUtf8("label_test"))
        self.verticalLayout_test.addWidget(self.label_test)
        self.comboBox_test_num = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_test_num.sizePolicy().hasHeightForWidth())
        self.comboBox_test_num.setSizePolicy(sizePolicy)
        self.comboBox_test_num.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox_test_num.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.comboBox_test_num.setFont(font)
        self.comboBox_test_num.setObjectName(_fromUtf8("comboBox_test_num"))
        self.verticalLayout_test.addWidget(self.comboBox_test_num)
        self.gridLayout_2.addLayout(self.verticalLayout_test, 1, 0, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_2, 7, 0, 1, 3)
        self.label = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_8.addWidget(self.label, 1, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_8.addWidget(self.label_5, 9, 0, 1, 1)
        self.pushButton_browse_save = QtGui.QPushButton(self.centralwidget)
        self.pushButton_browse_save.setObjectName(_fromUtf8("pushButton_browse_save"))
        self.gridLayout_8.addWidget(self.pushButton_browse_save, 6, 2, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButton_auto_threshold = QtGui.QPushButton(self.centralwidget)
        self.pushButton_auto_threshold.setObjectName(_fromUtf8("pushButton_auto_threshold"))
        self.horizontalLayout.addWidget(self.pushButton_auto_threshold)
        self.doubleSpinBox_threshold = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_threshold.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_threshold.setDecimals(4)
        self.doubleSpinBox_threshold.setMaximum(100.0)
        self.doubleSpinBox_threshold.setSingleStep(0.0001)
        self.doubleSpinBox_threshold.setObjectName(_fromUtf8("doubleSpinBox_threshold"))
        self.horizontalLayout.addWidget(self.doubleSpinBox_threshold)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout_8.addLayout(self.horizontalLayout, 10, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_8.addWidget(self.label_6, 11, 0, 1, 1)
        self.doubleSpinBox_add_stim_time = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_add_stim_time.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_add_stim_time.setDecimals(3)
        self.doubleSpinBox_add_stim_time.setMaximum(10.0)
        self.doubleSpinBox_add_stim_time.setSingleStep(0.001)
        self.doubleSpinBox_add_stim_time.setObjectName(_fromUtf8("doubleSpinBox_add_stim_time"))
        self.gridLayout_8.addWidget(self.doubleSpinBox_add_stim_time, 12, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_8, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 431, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Sparkle to Neuroscience Converter", None))
        self.pushButton_start.setText(_translate("MainWindow", "Start", None))
        self.label_3.setText(_translate("MainWindow", "Metadata", None))
        self.label_2.setText(_translate("MainWindow", "Output Directory:", None))
        self.pushButton_browse_open.setText(_translate("MainWindow", "Browse...", None))
        self.label_4.setText(_translate("MainWindow", "Data", None))
        self.label_comments.setText(_translate("MainWindow", "Comments:", None))
        self.label_test.setText(_translate("MainWindow", "Test Number:", None))
        self.label.setText(_translate("MainWindow", "Open:", None))
        self.label_5.setText(_translate("MainWindow", "Threshold:", None))
        self.pushButton_browse_save.setText(_translate("MainWindow", "Browse...", None))
        self.pushButton_auto_threshold.setText(_translate("MainWindow", "Estimate Threshold", None))
        self.doubleSpinBox_threshold.setSuffix(_translate("MainWindow", " V", None))
        self.label_6.setText(_translate("MainWindow", "Stimulus Window:", None))
        self.doubleSpinBox_add_stim_time.setToolTip(_translate("MainWindow", "The amount of time to add to the stimulus window and subtract from silence windows. CAUTION: This feature will add the desired time to all non-silence stimuli and remove the same amount of time from silence stimuli as long as it is not the first stimuli of the trace.", None))
        self.doubleSpinBox_add_stim_time.setPrefix(_translate("MainWindow", "+ ", None))
        self.doubleSpinBox_add_stim_time.setSuffix(_translate("MainWindow", " s", None))

